In [260]:
import numpy as np
import sqlite3
import pandas as pd
from ase.geometry import cell_to_cellpar
import os
import shutil

In [261]:
filename_db_all = "BZS_NEP_phase_transitions.db"
path_db_all = "./%s"%filename_db_all

connect_db_all = sqlite3.connect("file:%s?mode=ro"%filename_db_all, uri=True)
cursor_db_all = connect_db_all.cursor()

cursor_db_all.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor_db_all.fetchall()

print("Tables in the database:")
for table in tables:
    print(table[0])


Tables in the database:
systems
sqlite_sequence
species
keys
text_key_values
number_key_values
information


In [262]:
table_name = 'systems'
cursor_db_all.execute(f"PRAGMA table_info({table_name});")
schema = cursor_db_all.fetchall()
print(f"Schema for table {table_name}:")
for column in schema:
    print(column)

Schema for table systems:
(0, 'id', 'INTEGER', 0, None, 1)
(1, 'unique_id', 'TEXT', 0, None, 0)
(2, 'ctime', 'REAL', 0, None, 0)
(3, 'mtime', 'REAL', 0, None, 0)
(4, 'username', 'TEXT', 0, None, 0)
(5, 'numbers', 'BLOB', 0, None, 0)
(6, 'positions', 'BLOB', 0, None, 0)
(7, 'cell', 'BLOB', 0, None, 0)
(8, 'pbc', 'INTEGER', 0, None, 0)
(9, 'initial_magmoms', 'BLOB', 0, None, 0)
(10, 'initial_charges', 'BLOB', 0, None, 0)
(11, 'masses', 'BLOB', 0, None, 0)
(12, 'tags', 'BLOB', 0, None, 0)
(13, 'momenta', 'BLOB', 0, None, 0)
(14, 'constraints', 'TEXT', 0, None, 0)
(15, 'calculator', 'TEXT', 0, None, 0)
(16, 'calculator_parameters', 'TEXT', 0, None, 0)
(17, 'energy', 'REAL', 0, None, 0)
(18, 'free_energy', 'REAL', 0, None, 0)
(19, 'forces', 'BLOB', 0, None, 0)
(20, 'stress', 'BLOB', 0, None, 0)
(21, 'dipole', 'BLOB', 0, None, 0)
(22, 'magmoms', 'BLOB', 0, None, 0)
(23, 'magmom', 'REAL', 0, None, 0)
(24, 'charges', 'BLOB', 0, None, 0)
(25, 'key_value_pairs', 'TEXT', 0, None, 0)
(26, 'data', 

In [263]:
df_systems = pd.read_sql_query("SELECT id, cell FROM systems;", connect_db_all) #id, cell
pd.options.display.max_rows = 20
pd.options.display.max_seq_items = 20

# Decode BLOB into NumPy array
def decode_blob(blob_data):
    if blob_data is not None:
        return np.frombuffer(blob_data, dtype=np.float64).reshape(3, 3)
    return None

df_systems['decoded_cell'] = df_systems['cell'].apply(decode_blob)


#print(df_systems[['id', 'cell', 'decoded_cell']])
for i in range(0, len(df_systems[['decoded_cell']])):
    print(df_systems[['decoded_cell']].iloc[i][0])
    print("\n")

[[6.78355633 0.         0.        ]
 [0.         6.78355633 0.        ]
 [0.         0.         4.98887412]]


[[ 9.95317006e+00 -5.38134000e-03 -1.34450000e-04]
 [-4.32890000e-04  1.49246084e+01  2.65855000e-03]
 [-4.73046000e-03  1.07556000e-03  9.95235466e+00]]


[[ 5.08926156 -0.21331942  0.15094394]
 [-0.1799874   4.97411733  0.06119851]
 [ 0.13780578 -0.04126255  5.14795228]]


[[14.13206272 -2.35946227  2.87253067]
 [ 2.19437499 14.4146588   1.70322896]
 [-3.0617471  -1.11367056 14.35608087]]


[[ 5.15529246  0.          0.        ]
 [-0.          4.73051467  0.        ]
 [-0.         -0.          4.95377383]]


[[ 1.45376457e+01  1.52297218e+00  2.94590270e-01]
 [-1.36491855e+00  1.44931858e+01  4.44090000e-04]
 [-1.53827450e-01 -6.47323000e-02  1.45410875e+01]]


[[ -5.756366     8.10999201   8.4085938 ]
 [  7.83633791  -3.32332353  10.22066697]
 [  4.70799491   4.00773559 -11.93788193]]


[[-7.00168789  7.22434415  9.8631828 ]
 [ 7.00168789 -7.22434415  9.8631828 ]
 [ 7.00168

 [-0.18699779  0.11055527  5.24830632]]


[[ 7.30392038e+00  4.09368690e-01 -5.07097400e-02]
 [-8.97159000e-03  9.93560846e+00  8.42513300e-02]
 [ 2.01755060e-01 -3.10352680e-01  6.76523355e+00]]


[[13.11253102 -2.30611362 -5.93934175]
 [ 3.45914127 20.43650158 -0.04998706]
 [ 5.99147442 -1.16550307 13.32477102]]


[[ 7.31736499  0.39830923  0.01792779]
 [-0.3332394  10.30932862  0.1333449 ]
 [ 0.01501608  0.0443775   6.67266977]]


[[ -4.97166039   4.95759574  25.37343243]
 [  7.42155347  -7.433991    38.08224597]
 [  4.97205465   4.95291551 -25.38165717]]


[[ 1.41315679e+01 -1.10757600e-02  1.79131300e-02]
 [ 1.39015400e-02  1.98621566e+01  9.05959000e-03]
 [-1.79699400e-02  3.36719600e-02  1.38844509e+01]]


[[ -6.8959258    6.88653477  10.18189273]
 [  6.93924413  -6.93286593  10.16358235]
 [  6.89320943   6.9251546  -10.20265539]]


[[ -4.69695757   4.93683105  15.26492312]
 [  4.69695757  -4.93683105  15.26492312]
 [  7.04543636   7.40524658 -22.89738469]]


[[ 1.41346641e+01 -

 [ 3.49378697  3.49805288 -4.98143272]]


[[ 4.91288377e+00 -4.68230400e-02 -1.58407800e-02]
 [-5.19424400e-02  4.97091482e+00  1.15260000e-04]
 [-6.46658600e-02 -1.44947700e-02  5.00936613e+00]]


[[ 1.41494462e+01  2.23766800e-02 -2.25977800e-02]
 [ 3.18861000e-02  2.97434192e+01  4.65324100e-02]
 [-1.31141900e-02  2.36515800e-02  1.38624437e+01]]


[[ -7.44248642   7.44723559  23.36390822]
 [  4.87963869  -4.88148279  15.56169757]
 [  4.9924123    4.88368611 -15.56453077]]


[[-14.14918409   7.07234935  13.52407012]
 [  7.56320385 -11.92905686  15.0807453 ]
 [ 12.36216095  13.117474   -10.4794939 ]]


[[ 6.80419871  0.          0.        ]
 [ 0.         10.29021447  0.        ]
 [ 0.          0.          6.82426744]]


[[ 1.41068075e+01  5.39217000e-03  1.92261700e-02]
 [-4.13227300e-02  2.97962607e+01  6.64856300e-02]
 [ 6.93282000e-03 -9.99002000e-03  1.38589341e+01]]


[[ 2.07722627e+01  7.79960000e-04  2.03371300e-02]
 [ 1.81894800e-02  2.07846159e+01 -2.28260000e-04]
 [-1.97921

 [ 2.45604600e-02 -6.74393000e-03  6.89469783e+00]]


[[ 2.12067073e+01  7.65230000e-03 -1.37115400e-02]
 [ 6.86455000e-03  1.98085643e+01  1.22129200e-02]
 [ 3.02592000e-03 -4.90030000e-03  1.38484898e+01]]


[[ 2.07380446e+01 -2.33486000e-02 -6.44338000e-03]
 [-2.68062700e-02  2.07985789e+01 -3.86913800e-02]
 [-1.84477500e-02  1.47412200e-02  1.52918054e+01]]


[[ -7.43836852   7.44782466  38.06993873]
 [  4.96380306  -4.9622524   25.38451593]
 [  4.96977344   4.96537    -25.38979744]]


[[ 2.07797213e+01  1.96952900e-02 -1.66588100e-02]
 [-1.34572300e-02  2.07711761e+01 -4.21475000e-03]
 [-7.24064000e-03 -9.50457000e-03  1.53051988e+01]]


[[ -4.97090748   4.95891562  25.31453043]
 [  4.92440996  -4.96248204  25.31085036]
 [  7.46589897   7.42603727 -37.96543894]]


[[ 1.41351038e+01 -1.20084400e-02 -7.74738000e-03]
 [-2.95896800e-02  2.97175452e+01  1.17208000e-02]
 [ 1.67184600e-02 -2.23834400e-02  1.38485720e+01]]


[[-3.5096434   3.47963111  5.07000425]
 [ 3.387127   -3.40204335

 [ 1.21567650e-01 -3.26918000e-03  5.13777637e+00]]


[[ 6.86532746 -0.23720038 -0.02927889]
 [ 0.11717737  9.74452358  0.26215921]
 [-0.32982242 -0.47289796  6.84153541]]


[[ -7.40306334   7.39991626  23.33607854]
 [  4.9176825   -4.93316193  15.54815561]
 [  4.94863293   4.92487151 -15.55008559]]


[[ -6.89782871   4.86450184  11.00879956]
 [  9.79728076  -5.69440147   8.53034615]
 [  3.89139272   8.93533519 -10.19534443]]


[[ 5.48360832  0.          0.        ]
 [-0.          5.48360832  0.        ]
 [-0.         -0.          5.48360832]]


[[ 5.05276019  0.19387871  0.02931723]
 [ 0.05369307  4.8445863  -0.10018674]
 [-0.0754979   0.14461976  4.75954039]]


[[6.79123743 0.         0.        ]
 [0.         9.88043361 0.        ]
 [0.         0.         6.65709343]]


[[ 9.93533440e+00  1.48615900e-02 -6.48486000e-03]
 [-5.43481200e-02  1.49728655e+01 -1.86182600e-02]
 [-5.13232000e-03 -4.43000000e-02  9.94236093e+00]]


[[-4.15482501  4.15482501  5.35330488]
 [ 4.15482501 -4.15482

 [ 10.74656173  10.25568699 -15.09883697]]


[[ 9.77002168  2.64835265  0.05144021]
 [-2.73048058  9.86081072  0.35312785]
 [-0.21376992 -0.35181043 10.3488699 ]]


[[ 4.97233405e+00 -8.15040000e-04 -4.43520000e-03]
 [ 1.57062000e-03  4.97197390e+00 -6.33988000e-03]
 [-3.10986000e-03 -2.60159000e-03  4.97303493e+00]]


[[ 4.74983014  0.072295    0.06470654]
 [ 0.04486148  4.83490133 -0.05039127]
 [ 0.05696441  0.23353753  4.94245883]]


[[ -6.68808695   7.11988505   9.69705579]
 [ 10.03213044 -10.67982758  14.54558369]
 [  6.68808695   7.11988505  -9.69705579]]


[[ -7.4388866    7.43315286  38.00933401]
 [  4.95146861  -4.95442211  25.34128484]
 [  4.95849909   4.95401251 -25.34077005]]


[[ 7.21640591e+00  1.48029830e-01  3.65598000e-02]
 [-1.75168470e-01  9.72628536e+00  2.24656140e-01]
 [-9.08149000e-03 -3.24859420e-01  6.63735702e+00]]


[[ 7.12081067 -0.14083294 -0.33902355]
 [ 0.20630628 10.17860844  0.13957147]
 [-0.18305577 -0.04132051  7.11630126]]


[[ 1.49167540e+01 -3.0326

[[ 7.05501876  0.          0.        ]
 [ 0.          6.90572147  0.        ]
 [-0.          0.          4.85669656]]


[[12.96060387 -2.1303382  -0.7259167 ]
 [ 2.82120001 18.76201609 -3.40478557]
 [ 0.92219592  2.00919434 12.1081393 ]]


[[ 9.98108129  0.05687522 -0.05261784]
 [-0.01991271  9.93833212 -0.01849759]
 [ 0.01399111 -0.02546477  9.96041214]]


[[ -5.56678273   8.13690798  17.22977681]
 [ 10.63692277 -12.63779243  11.20809378]
 [  7.93445462  10.65454893 -14.83074175]]


[[-3.58333032  3.58318821  5.22014243]
 [ 3.58333032 -3.58318821  5.22014243]
 [ 3.58333032  3.58318821 -5.22014243]]


[[ 1.38789078e+01  1.57440500e-02 -2.71770000e-03]
 [ 3.14505900e-02  1.38434142e+01  4.42106100e-02]
 [ 4.03936300e-02  6.76816000e-03  1.02084767e+01]]


[[ 9.93656881e+00 -2.38540000e-03  4.44838000e-03]
 [ 1.38133500e-02  9.92046114e+00  9.59328000e-03]
 [ 1.14300900e-02 -2.35382900e-02  1.49335634e+01]]


[[-3.38815767  3.38815767  4.98178446]
 [ 3.38815767 -3.38815767  4.98178446]
 

 [-0.         -0.          4.75118726]]


[[13.88038901  0.          0.        ]
 [ 0.         13.46216304  0.        ]
 [-0.          0.         10.40993201]]


[[13.81456626  0.          0.        ]
 [ 0.         13.89983236  0.        ]
 [-0.          0.         16.00619581]]


[[ 4.99940222  0.00519018  0.21856555]
 [ 0.20652816  4.95338068 -0.22480446]
 [-0.23270004  0.01543811  4.88374191]]


[[ 9.97712525e+00 -1.04056400e-02 -2.83803200e-02]
 [-1.39862000e-03  1.48954289e+01 -1.68495700e-02]
 [ 1.97649200e-02  3.17339700e-02  9.96567088e+00]]


[[ 4.91120898  0.          0.        ]
 [-0.          5.17830991  0.        ]
 [-0.         -0.          4.87524069]]


[[ 9.76816168  0.          0.        ]
 [-0.         14.30038206  0.        ]
 [-0.         -0.         10.4004789 ]]


[[ -4.9495385    4.91431093  15.52340486]
 [  7.33988123  -7.47112976  23.3407374 ]
 [  4.95227119   4.96219301 -15.56394586]]


[[7.19126929 0.         0.        ]
 [0.         9.6807962  0.        ]
 

 [0.         0.         7.13557621]]


[[ -7.35282606   7.40942331  23.33724628]
 [  4.96374226  -4.96786911  15.60092451]
 [  4.88990255   4.9952832  -15.58166297]]


[[ 6.82674458  0.          0.        ]
 [ 0.          6.81111262  0.        ]
 [-0.          0.          5.05804814]]


[[ 7.13638598  0.          0.        ]
 [ 0.         10.29288711  0.        ]
 [ 0.          0.          6.82401207]]


[[ -7.35866458   7.41468455  23.33319679]
 [  7.44490602  -7.34966012  23.33612956]
 [  7.35270646   7.35529696 -23.33423483]]




In [264]:
df_species = pd.read_sql_query("SELECT * FROM species WHERE Z=56;", connect_db_all) #Z, n, id
df_unit_cell = pd.DataFrame(data={'id': [], 'cell': []})
df_unit_cubic = pd.DataFrame(data={'id': [], 'cell': []})
df_unit_tetrehedral = pd.DataFrame(data={'id': [], 'cell': []})
df_unit_orthohombic = pd.DataFrame(data={'id': [], 'cell': []})

strain_lim = [-0.05, 0.05]
cubic_in = pd.DataFrame([[4.9747931202880000, 0, 0], [0, 4.9747931202880000, 0], [0, 0, 4.9747931202880000]])
tetrahedral_in = pd.DataFrame([[6.9219962646660003, 0, 0], [0, 6.9219962646660003, 0], [0, 0, 5.0906878833290001]])
orthohombic_in = pd.DataFrame([[7.06714763, 0, 0], [0, 9.90634565, 0], [0, 0, 6.92224704]])


for i in range(0, len(df_species[['Z']])):
    df_temp = pd.DataFrame(data={'id': [i + 1], 'cell': [df_systems[['decoded_cell']].iloc[i][0]]})
    # Cubic
    if df_species[["n"]].iloc[i][0] == 1 and np.allclose(df_temp[["cell"]].iloc[0][0], cubic_in, atol = (1+strain_lim[1])*max(cubic_in)):
        #print("cubic:", df_species[["n"]].iloc[i][0],"\n", df_temp[["cell"]].iloc[0][0],"\n", "\n")
        df_unit_cell = pd.concat([df_unit_cell, df_temp], ignore_index=True)
        df_unit_cubic = pd.concat([df_unit_cubic, df_temp], ignore_index=True)
    # Tetrehedral
    elif df_species[["n"]].iloc[i][0] == 2 and np.allclose(df_temp[["cell"]].iloc[0][0], tetrahedral_in, atol = (1+strain_lim[1])*max(tetrahedral_in)):
        #print("tetrahedral:", df_species[["n"]].iloc[i][0],"\n", df_temp[["cell"]].iloc[0][0],"\n", "\n")
        df_unit_cell = pd.concat([df_unit_cell, df_temp], ignore_index=True)
        df_unit_tetrehedral = pd.concat([df_unit_tetrehedral, df_temp], ignore_index=True)
    # Orthohombic
    elif df_species[["n"]].iloc[i][0] == 4 and np.allclose(df_temp[["cell"]].iloc[0][0], orthohombic_in, atol = (1+strain_lim[1])*max(orthohombic_in)):
        #print("orthohombic:", df_species[["n"]].iloc[i][0],"\n", df_temp[["cell"]].iloc[0][0],"\n", "\n")
        df_unit_cell = pd.concat([df_unit_cell, df_temp], ignore_index=True)
        df_unit_orthohombic = pd.concat([df_unit_orthohombic, df_temp], ignore_index=True)

        
#print(df_systems[['id', 'decoded_cell']])
print(df_unit_cell)
#print(df_unit_cubic)
#print(df_unit_tetrehedral)
#print(df_unit_orthohombic)  # catches most cubic 2x2 supercells (177 4Ba entries)

         id                                               cell
0       1.0  [[6.78355633, 0.0, 0.0], [0.0, 6.78355633, 0.0...
1       3.0  [[5.08926156, -0.21331942, 0.15094394], [-0.17...
2       5.0  [[5.15529246, 0.0, 0.0], [-0.0, 4.73051467, 0....
3      10.0  [[5.09234635, 0.0, 0.0], [-0.0, 4.76114524, 0....
4      11.0  [[6.82156431, 0.0, 0.0], [0.0, 10.06963738, 0....
..      ...                                                ...
353  1178.0  [[7.36837377, -0.30528376, 0.17955777], [0.068...
354  1180.0  [[6.50716658, -0.0, 0.0], [0.0, 9.13296729, 0....
355  1183.0  [[6.93591632, 0.0, 0.0], [0.0, 9.80670867, 0.0...
356  1185.0  [[6.82674458, 0.0, 0.0], [0.0, 6.81111262, 0.0...
357  1186.0  [[7.13638598, 0.0, 0.0], [0.0, 10.29288711, 0....

[358 rows x 2 columns]


In [265]:
unit_cell_id = []
for i in range(0, len(df_unit_cell[["id"]])):
    unit_cell_id = np.append(unit_cell_id, int(df_unit_cell[["id"]].iloc[i][0]))

In [268]:
filename_db_unit = "unit_cells.db"
path_db_unit = "./%s"%filename_db_unit

if os.path.exists(path_db_unit):
    os.remove(path_db_unit)

shutil.copyfile(path_db_all, path_db_unit)

connect_db_unit = sqlite3.connect('file:%s' % path_db_unit, uri=True)
cursor_db_unit = connect_db_unit.cursor()

cursor_db_unit.execute("DELETE FROM species WHERE id NOT IN ({})".format(",".join("?" * len(unit_cell_id))), unit_cell_id)
cursor_db_unit.execute("DELETE FROM systems WHERE id NOT IN ({})".format(",".join("?" * len(unit_cell_id))), unit_cell_id)

connect_db_unit.commit()

print(pd.read_sql_query("SELECT id, cell FROM systems;", connect_db_unit))
print(pd.read_sql_query("SELECT * FROM species;", connect_db_unit))

connect_db_unit.close()

       id                                               cell
0       1  b'\xf4\xb1/\x97\\"\x1b@\x00\x00\x00\x00\x00\x0...
1       3  b'\xb3\xf5\xe3ag[\x14@S7@\xfe\x0cN\xcb\xbfT)\x...
2       5  b'\xc2\x0f\x94\xfc\x04\x9f\x14@\x00\x00\x00\x0...
3      10  b'\xb0\x9e\xa4\n\x90^\x14@\x00\x00\x00\x00\x00...
4      11  b"\x11\x0b\x8c'HI\x1b@\x00\x00\x00\x00\x00\x00...
..    ...                                                ...
353  1178  b'\xbaj;\xf96y\x1d@`\xcbL\xe5\xc4\x89\xd3\xbf\...
354  1180  b'\x8c\xe5\n\xadV\x07\x1a@\x00\x00\x00\x00\x00...
355  1183  b'K\xc5\x08\xd9`\xbe\x1b@\x00\x00\x00\x00\x00\...
356  1185  b'$\xfb\x94!\x96N\x1b@\x00\x00\x00\x00\x00\x00...
357  1186  b'\x80\xee.\xc4\xa8\x8b\x1c@\x00\x00\x00\x00\x...

[358 rows x 2 columns]
       Z   n    id
0     56   2     1
1     40   2     1
2     16   6     1
3     56   1     3
4     40   1     3
...   ..  ..   ...
1069  40   2  1185
1070  16   6  1185
1071  56   4  1186
1072  16  12  1186
1073  40   4  1186

[1074 rows x 3 

In [267]:
connect_db_all.close()